import React, { Component } from 'react';
import { connect } from 'react-redux';
import { selectBook } from '../actions/index';
import { bindActionCreators } from 'redux';
//the function in redux generated by Action creator gets connected to Reducers

class BookList extends Component {
  renderList() {
    return this.props.books.map((book) => {
      return (
        <li
          key={book.title}
          onClick={() => this.props.selectBook(book)} className="list-group-item">
          {book.title}
        </li>
      );
    });
  }

  render() {
    return (
      <ul className="list-group col-sm-4">
        {this.renderList()}
      </ul>
    )
  }
}

function mapStateToProps(state) {
  //take App State as argument, returns an object that will show up as props inside of BookList.  The glue between React and Redux.
  return {
    books: state.books
  };
}

//Anything returned from this function will end up as props on the BookList container

function mapDispatchToProps(dispatch) {
  //Whenever selectBook is called, results should be passed to all of our reducers
    return bindActionCreators({ selectBook: selectBook }, dispatch)
}

//Promote BookList from a component to a container, it needs to know about this new dispatch method, selectBook, make it available as a prop.
export default connect(mapStateToProps, mapDispatchToProps)(BookList)

//Connect takes in the function and the component, produces the container that can be passed down

//Container is a react component that has direct connection to state manage by redux
//React-redux is the bridge between React and Redux.  Smart component (container) injects the app. state in component
//The Most parent component that cares about state to be the container. BookList cares about the list of books
//the dumb component, app.js only cares about 'rendering' the view
// ONLY the MOST parent component needs to connect to Redux

//Whenever App. state changes, Container will re-render as well
